version: 2.1
executors:
  kotlin-build-container:
    working_directory: /home/circleci/project
    docker:
      - image: azul/zulu-openjdk:8
    environment:
      TZ: Asia/Tokyo
      _JAVA_OPTIONS: -Xmx2g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
      GRADLE_OPTS: -Xmx2g -Dorg.gradle.daemon=false
commands:
  internal-checkout:
    steps:
      - checkout
      - run:
          name: generate-cache-key
          command: |
            echo "${CIRCLE_SHA1}-${CIRCLE_BRANCH:-nil}-${CIRCLE_TAG:-nil}-`date "+%Y%m%d"`" > .cachekey
            cat .cachekey
  module-checkout:
    steps:
      - internal-checkout
      - restore_cache:
          key: configs-{{ checksum ".cachekey" }}
      - restore_cache:
          key: gradle-{{ checksum ".circleci/config.yml" }}-{{ checksum ".circleci/hash-gradle" }}
  module-save-cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: gradle-{{ checksum ".circleci/config.yml" }}-{{ checksum ".circleci/hash-gradle" }}
jobs:
  ##############################################
  # Build initialize
  ##############################################
  configure:
    executor:
      name: kotlin-build-container
    steps:
      - internal-checkout
      - run:
          name: snapshot-build-number
          command: |
            echo "$CIRCLE_BUILD_NUM" > .configs/secrets/build-number.env
      - save_cache:
          paths:
            - .configs/secrets
          key: configs-{{ checksum ".cachekey" }}
  ##############################################
  # unit-test
  ##############################################
  test:
    parameters:
      module:
        type: string
      localTestTask:
        type: string
        default: testDebug
      instrumentationTestTask:
        type: string
        default: assembleAndroidTest
      lintTask:
        type: string
        default: lintDebug
      formatTask:
        type: string
        default: format
    executor:
      name: kotlin-build-container
    steps:
      - module-checkout
      - run:
          name: compile
          command: |
            ./gradlew ":<< parameters.module >>:build"
      - run:
          name: format
          command: |
            ./gradlew "<< parameters.formatTask >>"
            if [ "`git status | grep '.kt'`" != "" ]; then
              echo "kotlin format error."
              echo "run -> ./gradlew format"
              exit 1
            fi
      - module-save-cache
      - store_artifacts:
          destination: archive-test-reports
          path: "<< parameters.module >>/build/reports"
      - store_artifacts:
          destination: archive-outputs
          path: "<< parameters.module >>/build/outputs"
      - store_test_results:
          destination: archive-outputs
          path: "<< parameters.module >>/build/test-results"
  ##############################################
  # deploy
  ##############################################
  deploy-to-bintray:
    executor:
      name: kotlin-build-container
    steps:
      - module-checkout
      - run:
          name: deploy
          command: ./gradlew bintrayUpload
aliases:
  - &depends-from-tests
    requires:
      - configure
  - &depends-from-deploy
    requires:
      - test
  - &filter-for-assemble
    filters:
      branches:
        only:
          - /^v[0-9].*/
          - /^feature\/id\/.*/
      tags:
        only:
          - /^v[0-9].*/
workflows:
  assemble-flow:
    jobs:
      - configure:
          context: bintray-maven
          <<: *filter-for-assemble
      - test:
          matrix:
            parameters:
              module:
                - swagger-codegen
          context: bintray-maven
          <<: *filter-for-assemble
          <<: *depends-from-tests
      - deploy-to-bintray:
          context: bintray-maven
          <<: *filter-for-assemble
          <<: *depends-from-deploy
# EOF
